training_pipeline_config:
  pipeline_name: application
  artifact_dir: storage


data_ingestion_config:
  dataset_download_url:  https://raw.githubusercontent.com/rodrigosantis1/backorder_prediction/master/dataset.rar
  raw_data_dir: raw_data
  tgz_download_dir: tgx_data
  ingested_dir: ingested_dir
  ingested_train_dir: train
  ingested_test_dir: test
  train_file_name: Kaggle_Training_Dataset_v2.csv
  test_file_name: Kaggle_Test_Dataset_v2.csv

data_validation_config:
  schema_dir: ConfigrationFiles
  schema_file_name: schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html


data_transformation_config:
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessed_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl

  